services:
  mysql:
    image: registry.cn-guangzhou.aliyuncs.com/foenye/mysql:9.7
    ports:
      - "3306:3306"
    volumes:
      - ./.gradle/volumes/mysql:/bitnami/mysql:rw
      - ./iddd_common/src/main/mysql/test_common.sql:/docker-entrypoint-initdb.d/01-test_common.sql:ro
      - ./iddd_common/src/main/mysql/common.sql:/docker-entrypoint-initdb.d/02-common.sql:ro
      - ./iddd_identityaccess/src/main/mysql/iam.sql:/docker-entrypoint-initdb.d/03-iam.sql:ro
      - ./iddd_collaboration/src/main/mysql/collaboration.sql:/docker-entrypoint-initdb.d/04-collaboration.sql:ro
    environment:
      BITNAMI_DEBUG: true
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iddd-mysql
      MYSQL_ENABLE_SLOW_QUERY: 1
      MYSQL_LONG_QUERY_TIME: 2
      MYSQL_EXTRA_FLAGS: >
        --default-time-zone=+08:00
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --lower-case-table-names=1
        --slow-query-log=1
        --slow-query-log-file=/bitnami/mysql/data/query-slow.log
        --long-query-time=2
        --local-infile=1
        --secure-file-priv=/tmp
        --innodb-redo-log-capacity=2G
        --innodb-log-buffer-size=512M
        --innodb-buffer-pool-size=2G
  rabbitmq:
    image: registry.cn-guangzhou.aliyuncs.com/foenye/rabbitmq:4.3
    environment:
      RABBITMQ_LOGS: "-"
      RABBITMQ_USERNAME: rabbit
      RABBITMQ_PASSWORD: rabbit
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "true"
      RABBITMQ_PLUGINS: rabbitmq_management rabbitmq_consistent_hash_exchange rabbitmq_stream rabbitmq_stream_management
      RABBITMQ_NODE_DEFAULT_QUEUE_TYPE: quorum
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - './.gradle/volumes/rabbitmqstats_data:/bitnami/rabbitmq/mnesia'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 10s
